services:
  - type: web
    name: mbongi-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mbongi_project.settings
